// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supplier_Site.Models;

#nullable disable

namespace Supplier_Site.Migrations
{
    [DbContext(typeof(SupplierDbContext))]
    partial class SupplierDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supplier_Site.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 234,
                            Name = "Eskom Holdings Limited",
                            TelephoneNo = "086 0037566"
                        },
                        new
                        {
                            Id = 2,
                            Code = 939,
                            Name = "Focus Rooms (Pty) Ltd",
                            TelephoneNo = "0820776910"
                        },
                        new
                        {
                            Id = 3,
                            Code = 34,
                            Name = "GSM Electro",
                            TelephoneNo = "0128110069"
                        },
                        new
                        {
                            Id = 4,
                            Code = 1264,
                            Name = "Jody and Herman Investments CC",
                            TelephoneNo = "0118864227"
                        },
                        new
                        {
                            Id = 5,
                            Code = 5667,
                            Name = "Johan Le Roux Ingenieurswerke",
                            TelephoneNo = "0233423390"
                        },
                        new
                        {
                            Id = 6,
                            Code = 667,
                            Name = "L. J. Ross t/a Petite Cafe'",
                            TelephoneNo = "0117868101"
                        },
                        new
                        {
                            Id = 7,
                            Code = 45,
                            Name = "L.A Auto Center  CC t/a LA Body Works",
                            TelephoneNo = "0219488412"
                        },
                        new
                        {
                            Id = 8,
                            Code = 1351,
                            Name = "LG Tow-In CC",
                            TelephoneNo = "0828044026"
                        },
                        new
                        {
                            Id = 9,
                            Code = 1352,
                            Name = "LM Greyling t/aThe Electric Advertiser",
                            TelephoneNo = "0119545972"
                        },
                        new
                        {
                            Id = 10,
                            Code = 1437,
                            Name = "M.H Cloete Enterprises (Pty) Ltd  t/a  Rola Motors",
                            TelephoneNo = "0218418300"
                        },
                        new
                        {
                            Id = 11,
                            Code = 67,
                            Name = "M.M Hydraulics CC",
                            TelephoneNo = "011425 6578"
                        },
                        new
                        {
                            Id = 12,
                            Code = 1980,
                            Name = "Phulo Human Capital (Pty) Ltd",
                            TelephoneNo = "0114755934"
                        },
                        new
                        {
                            Id = 13,
                            Code = 345,
                            Name = "Picaro 115 CC t/a H2O CT Services",
                            TelephoneNo = "0216745710"
                        },
                        new
                        {
                            Id = 14,
                            Code = 2279,
                            Name = "Safetygrip CC",
                            TelephoneNo = "0117086660"
                        },
                        new
                        {
                            Id = 15,
                            Code = 876,
                            Name = "Safic (Pty) Ltd",
                            TelephoneNo = "0114064000"
                        },
                        new
                        {
                            Id = 16,
                            Code = 2549,
                            Name = "The Financial Planning Institute Of Southern Africa",
                            TelephoneNo = "0861000374"
                        },
                        new
                        {
                            Id = 17,
                            Code = 935,
                            Name = "The Fitment Zone  CC",
                            TelephoneNo = "0118234181"
                        },
                        new
                        {
                            Id = 18,
                            Code = 2693,
                            Name = "Turnweld Engineering CC",
                            TelephoneNo = "0115468790"
                        },
                        new
                        {
                            Id = 19,
                            Code = 6,
                            Name = "Tutuka Motor Holdings Pty Ltd t/a Tutuka Motor Lab",
                            TelephoneNo = "0117044324"
                        },
                        new
                        {
                            Id = 20,
                            Code = 134,
                            Name = "WP Exhaust Brake & Clutch t/a In Focus Fleet Services",
                            TelephoneNo = "0219055028"
                        },
                        new
                        {
                            Id = 21,
                            Code = 3277,
                            Name = "WP Sekuriteit",
                            TelephoneNo = "0233421732"
                        },
                        new
                        {
                            Id = 22,
                            Code = 53,
                            Name = "Brietta Trading (Pty) Ltd",
                            TelephoneNo = "0115526000"
                        },
                        new
                        {
                            Id = 23,
                            Code = 392,
                            Name = "C.N. Braam t/a CNB Electrical Services",
                            TelephoneNo = "0832835399"
                        },
                        new
                        {
                            Id = 24,
                            Code = 625,
                            Name = "Creative Crew (Pty) Ltd",
                            TelephoneNo = "0120040218"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
